apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cj-hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cj-hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the cron job
          restartPolicy: OnFailure
